let a = 'hello';
let b = 'owu';
let c = 'com';
let d = 'ua';
let e = 1;
let f = 10;
let g = -999;
let h = 123;
const PI = 3.14;
let i = 16;
let j = true;
let k = false;

console.log(a);
console.log(b);
console.log(c);
console.log(d);
console.log(e);
console.log(f);
console.log(g);
console.log(h);
console.log(PI);
console.log(i);
console.log(j);
console.log(k);

let l = ['hello', 'owu', 'com', 'ua', 1, 10, -999, 123, 3.14, 16, true, false];

console.log(l[0]);
console.log(l[1]);
console.log(l[2]);
console.log(l[3]);
console.log(l[4]);
console.log(l[5]);
console.log(l[6]);
console.log(l[7]);
console.log(l[8]);
console.log(l[9]);
console.log(l[10]);
console.log(l[11]);